In [2]:
import numpy as np

In [59]:
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)

In [60]:
type(arr)
arr.shape

(5,)

In [12]:
my_lst_1 = [1,3,5,6,8]
my_lst_2 = [5,5,7,7,4]
my_lst_3 = [3,1,5,6,7]
two_arr = np.array([my_lst_1,my_lst_2,my_lst_3])

two_arr

array([[1, 3, 5, 6, 8],
       [5, 5, 7, 7, 4],
       [3, 1, 5, 6, 7]])

In [13]:
two_arr.shape

(3, 5)

In [17]:
two_arr.reshape(5,3)


array([[1, 3, 5, 6, 8, 5, 5, 7, 7, 4, 3, 1, 5, 6, 7]])

In [18]:
two_arr.reshape(1,15)

array([[1, 3, 5, 6, 8, 5, 5, 7, 7, 4, 3, 1, 5, 6, 7]])

In [26]:
two_arr

array([[1, 3, 5, 6, 8],
       [5, 5, 7, 7, 4],
       [3, 1, 5, 6, 7]])

In [35]:
two_arr[0:2,0:2]

array([[1, 3],
       [5, 5]])

In [40]:
two_arr[1:3,2:4]

array([[7, 7],
       [5, 6]])

In [46]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr = np.arange(0,10,4)

In [61]:
arr

array([1, 2, 3, 4, 5])

In [62]:
arr = np.linspace(1,10,50)
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [63]:
arr[3:] = 100
arr

array([  1.        ,   1.18367347,   1.36734694, 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        ])

In [69]:
arr1 = arr.copy()
arr1[:4] = 30
arr1

array([ 30.,  30.,  30.,  30., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100.])

In [70]:
arr >30


array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [71]:
arr * 2

array([  2.        ,   2.36734694,   2.73469388, 200.        ,
       200.        , 200.        , 200.        , 200.        ,
       200.        , 200.        , 200.        , 200.        ,
       200.        , 200.        , 200.        , 200.        ,
       200.        , 200.        , 200.        , 200.        ,
       200.        , 200.        , 200.        , 200.        ,
       200.        , 200.        , 200.        , 200.        ,
       200.        , 200.        , 200.        , 200.        ,
       200.        , 200.        , 200.        , 200.        ,
       200.        , 200.        , 200.        , 200.        ,
       200.        , 200.        , 200.        , 200.        ,
       200.        , 200.        , 200.        , 200.        ,
       200.        , 200.        ])

In [72]:
arr / 2

array([ 0.5       ,  0.59183673,  0.68367347, 50.        , 50.        ,
       50.        , 50.        , 50.        , 50.        , 50.        ,
       50.        , 50.        , 50.        , 50.        , 50.        ,
       50.        , 50.        , 50.        , 50.        , 50.        ,
       50.        , 50.        , 50.        , 50.        , 50.        ,
       50.        , 50.        , 50.        , 50.        , 50.        ,
       50.        , 50.        , 50.        , 50.        , 50.        ,
       50.        , 50.        , 50.        , 50.        , 50.        ,
       50.        , 50.        , 50.        , 50.        , 50.        ,
       50.        , 50.        , 50.        , 50.        , 50.        ])

In [73]:
arr % 2

array([1.        , 1.18367347, 1.36734694, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [74]:
np.ones(4,dtypes=int)

TypeError: ones() got an unexpected keyword argument 'dtypes'